Вам нужно защитить данные клиентов страховой компании. Надо разработать такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обосновать корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось.

## 1. Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('/datasets/insurance.csv')

In [3]:
df.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [4]:
df.to_csv('insurance.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Данные состроят из 5000 строк и 5 признаков. Пропусков нет. Типы данных в порядке. Предобработка не нужна. Целевой признак - "Страховые выплаты". 

## 2. Умножение матриц

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

In [6]:
# Готовим целевой признак и признаки
features=df.drop(['Страховые выплаты'],axis=1)
target=df['Страховые выплаты']

In [7]:
features.shape

(5000, 4)

In [8]:
target.shape

(5000,)

In [116]:
state = np.random.RandomState(12345)

In [122]:
# Формирую случайными равномерно распределнными значениями обратиму матрицу 4х4
inv_rand_matrix=np.random.normal(size=(features.shape[1],features.shape[1]))
inv_rand_matrix.shape

(4, 4)

In [123]:
# 
inv_rand_matrix 

array([[-0.10671327,  0.05189762, -0.39358786, -1.16208205],
       [-0.48869268, -0.41727505,  0.28254824, -0.84233516],
       [-0.43798894, -1.74977534, -0.42161085,  0.60993947],
       [ 0.93341622,  0.33397146, -0.20384075,  1.33279925]])

<span Способ RandomState для np</span>

In [20]:
# Формирую случайными равномерно распределнными значениями обратиму матрицу 4х4
state = np.random.RandomState(12345)
inv_rand_matrix=state.normal(size=(features.shape[1],features.shape[1]))
inv_rand_matrix

array([[-0.20470766,  0.47894334, -0.51943872, -0.5557303 ],
       [ 1.96578057,  1.39340583,  0.09290788,  0.28174615],
       [ 0.76902257,  1.24643474,  1.00718936, -1.29622111],
       [ 0.27499163,  0.22891288,  1.35291684,  0.88642934]])

In [10]:
# Новая кодированная матрица 
crypt_features=features.dot(inv_rand_matrix)

In [103]:
crypt_features

0            1             2             3
0    -27521.368184  7292.064854 -30243.324438 -25746.750120
1    -21106.798935  5604.351776 -23188.397131 -19724.670906
2    -11669.395418  3101.173149 -12819.025521 -10899.762127
3    -23118.873261  6116.672403 -25409.952579 -21647.967886
4    -14491.068071  3843.704127 -15922.136949 -13547.242932
...            ...          ...           ...           ...
4995 -19807.211588  5247.944949 -21766.195337 -18532.734111
4996 -29061.837078  7694.737103 -31939.324807 -27200.912915
4997 -18798.878440  4975.881230 -20660.631916 -17598.835314
4998 -18137.179321  4801.362940 -19932.481480 -16976.471149
4999 -22519.359418  5962.343095 -24748.752751 -21075.461476

[5000 rows x 4 columns]

In [104]:
# пример матрицы признаков X
features

Пол  Возраст  Зарплата  Члены семьи
0       1     41.0   49600.0            1
1       0     46.0   38000.0            1
2       0     29.0   21000.0            0
3       0     21.0   41700.0            2
4       1     28.0   26100.0            0
...   ...      ...       ...          ...
4995    0     28.0   35700.0            2
4996    0     34.0   52400.0            1
4997    0     20.0   33900.0            2
4998    1     22.0   32700.0            3
4999    1     28.0   40600.0            1

[5000 rows x 4 columns]

In [105]:
# пример преобразованной матрицы признаков B
crypt_features

0            1             2             3
0    -27521.368184  7292.064854 -30243.324438 -25746.750120
1    -21106.798935  5604.351776 -23188.397131 -19724.670906
2    -11669.395418  3101.173149 -12819.025521 -10899.762127
3    -23118.873261  6116.672403 -25409.952579 -21647.967886
4    -14491.068071  3843.704127 -15922.136949 -13547.242932
...            ...          ...           ...           ...
4995 -19807.211588  5247.944949 -21766.195337 -18532.734111
4996 -29061.837078  7694.737103 -31939.324807 -27200.912915
4997 -18798.878440  4975.881230 -20660.631916 -17598.835314
4998 -18137.179321  4801.362940 -19932.481480 -16976.471149
4999 -22519.359418  5962.343095 -24748.752751 -21075.461476

[5000 rows x 4 columns]

Умножая значения одних и тех же весов на признаки разных матриц  мы получим значения отличные друг от друга

**Ответ:** при умножении признаков $X$ на обратимую матрицу $P$ мы имеем новую матрицу признаков $B$. Качество линейной регрессии после проверки $B$ измениться, т.е метрика качества $R^2$ будет сильно другой. А точнее будет хуже. Но если принять матрицу признаков $B$, как обучающую, то модель обучится и покажет тот же результат $R^2$, что и для признаков $X$  


**Обоснование:** в нашей задаче мы предсказываем целевой признак $y=W1*X1+W2*X2...Wn*Xn+W0$, где n-количество признаков. А если мы подставим вместо значений $X$ значения новой матрицы $B$, то получим значения новых предсказаний $y'$: $y'=W1*В1+W2*В2...Wn*Вn+W0$, и при старых весах $W$ значения $y!=y'$. Для того чтобы получить $y=y'$ надо получить новые веса $W'$, т.е обучить матрицу признаков $B$ заново! 

## 3. Алгоритм преобразования

**Алгоритм**

После получения новой матрицы B, перед процессом функцией predict выполним действие: $X=P^{-1}*B$

**Обоснование**

Кодирование признаков происходит умножением $X*P=B$, где  $X$-матрица признаков, $P$-матрица, на которую умножаются признаки (обратимая матрица),$B$-новая матрица.
Умножим обе части уравнения на $Р^{-1}$ (обратную матрицу $P$). Получим $X*Р^{-1}*P=B*Р^{-1}$. Зная свойство обратных матриц $Р^{-1}*P=E$, где Е- это единичная матрица и зная свойство единичной матрицы $E*X=X$, получаем, что $X=P^{-1}*B$

## 4. Проверка алгоритма

In [106]:
# Класс модели линейной регрессии
class LineRegression():
    #Функция обучения
    def fit(self,train_features,train_target):
       
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1) # Добавляем столбец с 1
        y=train_target 
        w=np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y) # сама формула ЛР
       
        self.w=w[1:] # веса признаков
        self.w0=w[0] # регрессор константа
    
    #Функция предсказания    
    def predict(self,test_features):
        return test_features.dot(self.w)+self.w0 # признак 
     

In [107]:
# Модель линейной регрессии для features без кодирования
model=LineRegression()
model.fit(features,target)
prediction=model.predict(features)

MSE=r2_score(target,prediction)
print(MSE)

0.4249455028666801


In [108]:
# Модель линейной регрессии для crypt_features (кодированная) без обучения 
model=LineRegression()
model.fit(features,target)
prediction_crypt_1=model.predict(crypt_features)
MSE_crypt_1=r2_score(target,prediction_crypt_1)
print(MSE_crypt_1)

-488014.415724385


In [109]:
# Модель линейной регрессии для crypt_features (кодированная) с обучением 
model=LineRegression()
model.fit(crypt_features,target)
prediction_crypt_2=model.predict(crypt_features)
MSE_crypt_2=r2_score(target,prediction_crypt_2)
print(MSE_crypt_2)

0.4249455028666307


#### Реализация алгоритма преобразования

In [110]:
P=inv_rand_matrix 

In [111]:
P_inv=np.linalg.inv(inv_rand_matrix) # делаем обратную матрицу от inv_rand_matrix

In [112]:
ones_diag_matrix=P.dot(P_inv) # проверяем, что при их умножении будет единичная матрица
ones_diag_matrix

array([[ 1.00000000e+00,  7.06420537e-17, -1.76519409e-16,
         1.82793194e-16],
       [-3.46993212e-16,  1.00000000e+00, -1.06652082e-16,
        -5.90667247e-16],
       [-9.84661340e-18, -7.18470874e-17,  1.00000000e+00,
         2.89856525e-16],
       [-1.26475677e-17, -1.31463187e-16,  2.36917125e-16,
         1.00000000e+00]])

In [113]:
decrypt_features=crypt_features.dot(P_inv) # сам алгоритм преобразования

In [114]:
model=LineRegression()
model.fit(features,target)
prediction_decrypt=model.predict(decrypt_features)
MSE_decrypt=r2_score(target,prediction_decrypt)
print(MSE_decrypt)

0.4249455028666862


### Сравнение качества моделей

In [115]:
rezume=[MSE,MSE_crypt_1,MSE_crypt_2,MSE_decrypt]
df_rezume=pd.DataFrame(rezume,index=['Без кодирования','С кодированием и без переобучения','С кодированием и переобучением','С преобразованием'])
df_rezume.set_axis(['MSE'],axis='columns',inplace=True)
df_rezume

MSE
Без кодирования                         0.424946
С кодированием и без переобучения -488014.415724
С кодированием и переобучением          0.424946
С преобразованием                       0.424946

Модели "Без кодирования","С кодированием и переобучением" и "С преобразованием	" дали одинаковый результат. Алгоритм преобразования работает!